### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by JuniorDevTun** [JuniorTun/juniordev.tn#2]
Make the website responsive (tablet, phone, desktop)

**Comment by bedouijesser** [comment]
Minor changes to the  "hero section":
`#hero-section {
    width: 100%;
    height: 300px;
    margin: 3rem 0;
    display: flex;
    justify-content: center;
}
#hero-section #main-card {
    padding: 1rem;
    width: 700px;
    border: 1px solid rgba(38, 38, 38, 0.4);
    border-radius: .2rem;
    -webkit-box-shadow: 10px 10px 0 #262626;
    box-shadow: 10px 10px 0 #262626;
}
#hero-section #main-card #search-box label input {
    width: 80%;
    border: none;
    height: 2em;
    outline: none;
}
#search-box i {
    line-height: 2;
}
`
check it out :D

**Comment by bedouijesser** [comment]
Add a "Junior Dev" label next to the Logo at the top

**Comment by AymKh** [comment]
> 
> 
> Minor changes to the "hero section":
> `#hero-section { width: 100%; height: 300px; margin: 3rem 0; display: flex; justify-content: center; } #hero-section #main-card { padding: 1rem; width: 700px; border: 1px solid rgba(38, 38, 38, 0.4); border-radius: .2rem; -webkit-box-shadow: 10px 10px 0 #262626; box-shadow: 10px 10px 0 #262626; } #hero-section #main-card #search-box label input { width: 80%; border: none; height: 2em; outline: none; } #search-box i { line-height: 2; } `
> check it out :D

this will center the card and give it a large padding at the bottom, which is not the look we're going for

**Comment by AymKh** [comment]
> 
> 
> Add a "Junior Dev" label next to the Logo at the top

Will work on that tonight
